version: '3.3'

volumes:
  data:
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=clea
      - MYSQL_DATABASE=clea_user_db
  app:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
