version: '3.3'

volumes:
  data:
services:
    astrolab-config-server:
        image: astrolabweb/astrolab-config-server:latest
        ports:
                - "9090:9090"
    astrolab-eureka-server:
        image: astrolabweb/astrolab-eureka-server:latest
        depends_on:
                - "astrolab-config-server"
        ports:
                - "9091:9091"
